"use client"
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Wraper from "@/Layout/Wraper";


import { QueryClientProvider, QueryClient } from "react-query";
import StoreProvider from "@/Redux/StoreProvider";
const query = new QueryClient();




const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

 const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <StoreProvider>
       <QueryClientProvider client={query}>
        <Wraper>
        {children}
        </Wraper>
        </QueryClientProvider>
        </StoreProvider>
        
      </body>
    </html>
  );
}
